# -*- coding: utf-8 -*-
"""Copper News Llama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1us4b-pSGGE_mggzZ5bblNJF8451-yJdP

checking gpu t4 is available
"""

!lsb_release -a

import tensorflow as tf
from psutil import virtual_memory

# Check GPU
gpu_info = tf.config.list_physical_devices('GPU')
print(f"GPU Info: {gpu_info}")

# Check RAM
ram_info = virtual_memory()
print(f"Total RAM: {ram_info.total / (1024**3)} GB")

# Commented out IPython magic to ensure Python compatibility.
!pip install colab-xterm #https://pypi.org/project/colab-xterm/
# %load_ext colabxterm

!pip install colab-xterm -qqq
!pip install langchain -qqq
!pip install langchain_community -qqq

"""Opening Terminal
Next, open a terminal window within Colab:
"""

!curl -fsSL https://ollama.com/install.sh | sh

import subprocess
subprocess.Popen(["ollama", "serve"])

!ollama pull llama3.1

!pip install -U langchain-ollama

# Import Ollama module from Langchain
from langchain_community.llms import Ollama

# Initialize an instance of the Ollama model
llm = Ollama(model="llama3.1")
# Invoke the model to generate responses
response = llm.invoke("What is the capital of Chile?")
print(response)

"""# Caso Análisis Copper News

Pondremos a prueba las capacidades de entendimiento de lenguaje natural de LlaMA pidiendole que clasifique noticias relacionadas (o no) al mercado del cobre según si tendrían un efecto positivo, negativo o neutral en el precio futuro del cobre.
"""

import pandas as pd

# Cargar directamente tu archivo que ya está en /content/
df_noticias = pd.read_excel('/content/Noticias_Cobre_2022-2025_Final.xlsx')

# Verificar que se cargó correctamente
print(f"Total noticias: {len(df_noticias)}")

df_noticias

"""##Clasificación
El promt definirá si el la noticia afecta al precio del cobre de manera positiva, negativa o sin efecto alguno.

Se crea una función que le pida a Llama lo que se espera de éste. La mayoría de los LLMs espera como input un texto o prompt que tiene tres partes. Un SYSTEM prompt, un USER prompt, y un ASSISTANT prompt.
El system prompt le define un comportamiento por defecto, el user prompt es la parte que puede ir variando en la medida que se va conversando. El assistant prompt normalmente se usa para mostrar cómo deberia responder el modelo.

En este caso, el prompt se basa en 2 metodologías de promopting: role-play y ejemplos de eventos de clasificación.

"""

from langchain_community.llms import Ollama
from langchain_core.prompts import ChatPromptTemplate

# Initialize the Ollama model with your parameters
llm = Ollama(model="llama3.1", temperature=0.0, top_p=0.9, top_k=100)

# Define the function to analyze reviews and return pipe-separated output
def analiza_review(review):
    # Create the prompt template with a pipe-separated format
    prompt = ChatPromptTemplate.from_messages([
        ("system", """Eres un asistente de news analytics que usará sus habilidades de entendimiento profundo del lenguaje. Tu tarea será revisar las descripciones de diversas noticas relacionadas al cobre/cooper y a la industria.
              Estas noticias poseen información que afectan de alguna forma el precio del metal rojo (cobre), ya sea de manera negativa, positiva o neutra.
              Por lo tanto, debes clasificar la noticia como positivo cuando la noticia afecte de menra positiva el precio, es decir, aumente el precio. Otra opción es que la notica efecte de manera negativa, es decir, tenga efecto para disminuir el precio del cobre. Por último ver si el efecto es neutro.
              Las noticias pueden tratarse de diversos tópicos/categorías, como por ejemplo: huelgas, producción, oferta, demanda, etc.
              Te muestra el efecto que tienen algunas de las categorías
              Huelga:

Efecto positivo: hay huelga o se inicia una huelga.

Efecto negativo: termina la huelga o se resuelve el conflicto.

Efecto neutro: no ocurre la huelga porque se llega a un acuerdo o no se menciona conflicto laboral relevante.

Producción:

Efecto positivo: la producción de cobre está en disminución.

Efecto negativo: la producción de cobre está en aumento.

Efecto neutro: la producción se mantiene estable o no cambia de forma relevante.

Inventario:

Efecto positivo: los inventarios de cobre están en disminución.

Efecto negativo: los inventarios de cobre están en aumento.

Efecto neutro: los inventarios se mantienen estables o sin cambios relevantes.

Oferta:

Efecto positivo: la oferta de cobre está en disminución.

Efecto negativo: la oferta de cobre está en aumento.

Efecto neutro: la oferta se mantiene estable o no cambia de forma relevante.

Demanda:

Efecto positivo: la demanda de cobre está en aumento.

Efecto negativo: la demanda de cobre está en disminución.

Efecto neutro: la demanda se mantiene estable o no cambia de forma relevante.

Tu tarea es leer la noticia y, para cada una indicar si el efecto en el precio del cobre es positivo, negativo o neutro.
Recuerda que no solo existen los tópicos que te mencioné previamente, estos son variados y debes ver el efecto que tiene cada noticia en el precio del cobre.
"""),
        ("user", f"""Aquí tienes un review, por favor analizalo: "{review}"\n
            El output debe estar en español y tener la siguiente estructura:\n
            Efecto:positivo, neutro o negativo
            No es necesario ninguna explicación previa o justificación posterior, sólo devuelvelo en el formato especificado. Toda respuesta debe tener solo el Efecto.
            """)
    ])

    # Invoke the model with the provided review
    chain = prompt | llm
    out = chain.invoke({"review": review})

    # Return the response
    return out

"""Probemos la función que aplicará el prompt creado:"""

mireview = df_noticias.loc[1, 'Resumen']
mireview

analiza_review(mireview)

"""### Batch Análisis o Análisis Masivo

Ddo que el prompt se creó como una función de python, ahora se puede ocupar de manera sistemática, por ejemplo, para análizar una base de datos con cientos de noticias.
En python, usando pandas, es tan "simple" como definir la columna del DF que queremos analizar, y aplicar la función creada con el comando "apply"... En esta caso, corresponde a la columna "Resumen", la cual entrega una breve descripción del contenido de la noticia.
"""

#esto puede tomar un tiempo dado que estamos usando la versión "gratuita" de google colab, la cual no posee un hardware tan poderoso
#ten paciencia...

df_noticias['llama_análisis']=df_noticias['Resumen'].apply(analiza_review)

"""El resultado de la clasificación entregada por el modelo es posible visualizarla en la columna "llama_analisis"
"""

df_noticias

import pandas as pd

# Suponemos que ya tienes cargado el DataFrame
# df_noticias = pd.read_excel('tu_archivo.xlsx')

def extraer_efecto(texto):
    """
    Recibe algo como 'Efecto: positivo' o 'Efecto:negativo'
    y devuelve solo 'positivo', 'negativo' o 'neutro'.
    """
    if not isinstance(texto, str):
        return None

    # Asegurarse de que contenga la palabra 'Efecto'
    if "Efecto" not in texto:
        return None

    # Separar por ':' y tomar la parte derecha
    partes = texto.split(":")
    if len(partes) < 2:
        return None

    efecto = partes[1].strip().lower()  # limpiar espacios y normalizar

    # Opcional: normalizar valores esperados
    if efecto.startswith("posi"):
        return "positivo"
    if efecto.startswith("nega"):
        return "negativo"
    if efecto.startswith("neut"):
        return "neutro"

    return efecto  # por si viene escrito de otra forma pero quieres conservarlo

# Crear nueva columna con el efecto limpio
df_noticias["efecto_modelo"] = df_noticias["llama_análisis"].apply(extraer_efecto)

# Verificar resultado
print(df_noticias[["llama_análisis", "efecto_modelo"]].head())

df_noticias

#siempre podemos llevar nuestros resultados de vuelta a excel
df_noticias.to_excel('Analisis_Llama_Noticia.xlsx')