# -*- coding: utf-8 -*-
"""Extraccion de Noticias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwHoCwRIhJROzoFDWkiNhOSqC-fvxRNK
"""

# Búsqueda iterativa mes a mes usando GoogleNews dede Junio 2022 - Octubre 2025

# Instalar librerías
import subprocess
import sys
import time
import random
import pandas as pd
from datetime import datetime, timedelta
print("Instalando librerías necesarias...")
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "GoogleNews", "pandas", "openpyxl", "requests"])
from GoogleNews import GoogleNews

print("\n✓ Librerías instaladas. Iniciando proceso de Deep Search...")

# Definir las palabras clave para rotar y no saturar
# Mezclar inglés y español para cobertura global (Chile, Perú, USA, China)
KEYWORDS = [
    "Copper price mining",
    "Precio cobre Chile",
    "Copper mining production",
    "Mercado cobre Perú",
    "Copper supply demand",
    "Minera cobre huelga",
    "Copper shortage",
    "Codelco producción"
]

# Lista para guardar resultados
all_news = []

# Función para generar rangos de fechas mensuales
def generate_monthly_ranges(start_date, end_date):
    current = start_date
    while current < end_date:
        next_month = current.replace(day=28) + timedelta(days=4)
        last_day_of_month = next_month - timedelta(days=next_month.day)
        if last_day_of_month > end_date:
            last_day_of_month = end_date
        yield current, last_day_of_month
        current = last_day_of_month + timedelta(days=1)

# Definir fechas de inicio y fin
START_DATE = datetime(2022, 6, 1)
END_DATE = datetime(2025, 10, 30)

# Búsqueda iterativa mensual

print(f"\n INICIANDO BÚSQUEDA HISTÓRICA ({START_DATE.strftime('%m/%Y')} - {END_DATE.strftime('%m/%Y')})")
print("="*70)

googlenews = GoogleNews()

for start, end in generate_monthly_ranges(START_DATE, END_DATE):

    # Formato de fecha para la librería: MM/DD/YYYY
    d_start = start.strftime('%m/%d/%Y')
    d_end = end.strftime('%m/%d/%Y')

    # Elegir una keyword aleatoria para variar la búsqueda cada mes
    keyword = random.choice(KEYWORDS)

    print(f" Procesando mes: {start.strftime('%Y-%m')} | Keyword: '{keyword}'...")

    try:
        # Configurar la búsqueda para ese mes específico
        googlenews = GoogleNews(start=d_start, end=d_end)
        googlenews.set_lang('en') # Alternar idioma base (muchas noticias están en inglés)
        if random.random() > 0.5: # 50% de probabilidad de buscar en español
            googlenews.set_lang('es')

        googlenews.search(keyword)

        # Obtenemos resultados
        results = googlenews.result()

        # Procesamos y limpiamos los resultados de este mes
        count_month = 0
        for item in results:
            title = item.get('title', '')
            link = item.get('link', '')
            date_str = item.get('date', '')
            media = item.get('media', '')

            # Filtro básico de calidad
            if len(title) > 10 and link.startswith('http'):
                # Intentamos arreglar la fecha si es relativa
                fecha_excel = start.strftime('%d/%m/%Y')

                all_news.append({
                    'Fecha (dd/mm/yyyy)': fecha_excel, # Fecha aproximada (mes correcto)
                    'Link': link,
                    'Titular': title,
                    'Resumen': f"Fuente: {media}. Noticia histórica recuperada del periodo {start.strftime('%B %Y')}.",
                    'Fuente_Origen': f"GoogleNews ({media})"
                })
                count_month += 1

        print(f"   Encontradas: {count_month} noticias.")

        # Limpiamos para la siguiente iteración
        googlenews.clear()

        # Pausa de respeto para no ser bloqueados por Google (IMPORTANTE)
        time.sleep(random.uniform(2, 4))

    except Exception as e:
        print(f"   Error en este mes: {e}")
        time.sleep(5)

# ============================================================================
# 4. GUARDADO DE RESULTADOS
# ============================================================================

print("\n" + "="*70)
print("PROCESAMIENTO FINAL")

if len(all_news) > 0:
    df = pd.DataFrame(all_news)

    # Eliminamos duplicados exactos
    df.drop_duplicates(subset=['Titular'], inplace=True)

    # Guardamos
    filename = 'Noticias_Cobre_DeepSearch_2022_2025.xlsx'
    df.to_excel(filename, index=False)

    print(f"\n ÉXITO TOTAL: Se han recopilado {len(df)} noticias históricas.")
    print(f"Archivo guardado: {filename}")
    print(" Descárgalo desde la carpeta de archivos de Colab.")

    # Mostrar muestra
    print("\nEjemplo de noticias encontradas:")
    print(df[['Fecha (dd/mm/yyyy)', 'Titular']].head(5).to_string())
else:
    print("\n No se encontraron noticias. Google pudo haber bloqueado las peticiones temporales.")
    print("Intenta ejecutarlo nuevamente en unos minutos o cambia la IP si es posible.")